# Generated by Django 3.0.3 on 2020-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric_type', models.CharField(choices=[('Tmax', 'Tmax'), ('Tmin', 'Tmin'), ('Rainfall', 'Rainfall')], max_length=128)),
                ('metric_value', models.SmallIntegerField()),
                ('location', models.CharField(choices=[('UK', 'UK'), ('England', 'England'), ('Wales', 'Wales'), ('Scotland', 'Scotland')], max_length=128)),
            ],
        ),
    ]
